### Criar uma nova task
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "description": "Descrição da tarefa3",
  "userId": "6d05c473-7a06-45bd-bcf1-4496e4757fd2"
}

### Atualizar uma task
PATCH http://localhost:3000/tasks/0ccf3f3d-e508-473c-aba7-3cb3b02efa5a
Content-Type: application/json

{
  "description": "Descrição atualizada2"
}

### Remover uma task
DELETE http://localhost:3000/tasks/0ccf3f3d-e508-473c-aba7-3cb3b02efa5a

### Listar todas as tasks de um usuário
GET http://localhost:3000/tasks/user

