### Criar uma nova task
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "Nova Tarefa",
  "description": "Descrição da tarefa",
  "userId": "123"
}

### Atualizar uma task
PATCH http://localhost:3000/tasks/353ec5de-e6ba-42df-a00d-d7bae968de62
Content-Type: application/json

{
  "title": "Tarefa Atualizada",
  "description": "Descrição atualizada"
}

### Remover (soft delete) uma task
DELETE http://localhost:3000/tasks/c1ae7715-d8a7-4c80-8163-ac3fe769ddfd

### Listar todas as tasks de um usuário
GET http://localhost:3000/tasks/user/123

### Listar todas as tasks
GET http://localhost:3000/tasks
