version: '3.8'

services:
  database:
    image: postgres:17
    container_name: demaria_db
    restart: always
    environment:
      POSTGRES_USER: demaria
      POSTGRES_PASSWORD: demariapassword
      POSTGRES_DB: demaria
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: demaria_api
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: sh -c "npm run start:dev && sleep 60 && psql -h database -U demaria -d demaria -f /app/seed.sql"

volumes:
  pgdata:
