### Criação de Usuário
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@demaria.com",
  "password": "admin"
}

### Listar Todos os Usuários
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM2YTdjMjY2LTg5MGEtNDJlOS1iYzgwLTk3NDNmOTNjZDc0NCIsImVtYWlsIjoiYWRtaW5AZGVtYXJpYS5jb20uYnIiLCJ1c2VyX3R5cGUiOjIsImlhdCI6MTc0MjM5MzIxOCwiZXhwIjoxNzQyMzk2ODE4fQ.yBEnuoDpN6BLoBLeWwi8c8TepYLGA9D22TwCdfiFVBc

### Atualizar Usuário
PATCH http://localhost:3000/users/f9c426c6-caa4-4125-bcf7-8112556dac38
Content-Type: application/json


{
  "name": "João Silva Atualizado",
  "email": "joao.silva7.atualizado@example.com"
}

### Soft Delete de Usuário
PATCH http://localhost:3000/users/softdelete/f9c426c6-caa4-4125-bcf7-8112556dac38
