### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Usuário 1",
  "email": "usuaro131asd31233@email.com",
  "password": "senha123"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "usuario1@email.com",
  "password": "senha123"
}
