### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Admin",
  "email": "admi1n@demaria.com.br",
  "password": "adminpassword"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
 "email": "admin@demaria.com",
  "password": "demaria"
}
